Failing scraper slack notification
CodeForAfrica-SCRAPERS/healthtools_ke pull request #10
Opened 2017-06-20 13:29 UTC by Gathondu

#### What does this PR do?
Sends a slack message if a scrapper fails
#### Description of Task to be completed?
Notification on Slack of failing scraper
#### How should this be manually tested?
run the following command:
`nosetests healthtools.tests.test_scrapers:TestDoctorsScraper.test_scrapper_sends_slack_notification`
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/18587173/27335351-d095b0da-55d4-11e7-9c82-6aea3a4beab2.png)

2017-06-20 13:32 UTC, Gathondu commented
@DavidLemayian this PR Depends on the Indexing PR. every change there is also here but I have updated the README on this PR

2017-06-20 17:26 UTC, Gathondu commented
@DavidLemayian this is the other branch I keep referring to. 😄

2017-06-20 18:29 UTC, DavidLemayian commented
@Gathondu The #9 has caused conflicts with this. Make the pull and do the necessary.

2017-06-21 07:01 UTC, Gathondu commented
@DavidLemayian i've handled the conflicts..we good to go

2017-06-21 07:51 UTC, DavidLemayian requested changes

2017-06-21 07:51 UTC, DavidLemayian commented on healthtools/config.py
> +    "region_name": os.getenv("MORPH_AWS_REGION")
Let's have this default to `eu-west-1`.

2017-06-21 07:51 UTC, DavidLemayian commented on healthtools/scrapers/base_scraper.py
> +                    )
Due to repeating nature, this should probably be handled as a method.

2017-06-21 07:51 UTC, DavidLemayian commented on healthtools/scrapers/base_scraper.py
> -            print "ERROR - delete_elasticsearch_docs() - {} - {}".format(type(self).__name__, str(err))
We should still maintain error logs being printed incase Slack is not preferred / used by other people who pick up this code. Also, dev environments might prefer not to send to Slack.

2017-06-21 07:51 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +        self.assertEqual(response.status_code, 200)
👍 on the test add.

2017-06-21 07:51 UTC, DavidLemayian commented
@Gathondu Have you also checked out whether this could be useful? - https://github.com/mathiasose/slacker_log_handler

2017-06-21 09:23 UTC, Gathondu commented on healthtools/scrapers/base_scraper.py
> +                    )
very true..on it

2017-06-21 09:23 UTC, Gathondu commented on healthtools/scrapers/base_scraper.py
> -            print "ERROR - delete_elasticsearch_docs() - {} - {}".format(type(self).__name__, str(err))
I have maintained the printing to the terminal on all errors. That should be the merge conflict bit that i had to remove

2017-06-21 09:58 UTC, Gathondu commented
I've checked this out `https://github.com/mathiasose/slacker_log_handler` and i noticed it uses an API KEY. From slack's documentation we need to use OAuth to get the access token and this means using a web server and I was shy to use that approach since this is just a scrapper and adding a web server just to get a token was an overkill hence the webhook approach. We could use the legacy token approach but that's for testing purposes and this is how it was posting on slack: 
![image](https://user-images.githubusercontent.com/18587173/27378642-424c3e22-5681-11e7-86eb-3b27a9806d4b.png)
and I had no control whatsoever on the handle's title

2017-06-21 11:13 UTC, Gathondu commented
@DavidLemayian I have already made the requested changes

2017-06-21 17:15 UTC, DavidLemayian requested changes

2017-06-21 17:15 UTC, DavidLemayian commented on healthtools/scrapers/base_scraper.py
>                  print "ERROR: scrape_site() - source: {} - page: {} - {}".format(url, page_num, err)
Considering the error message is the same printed and to Slack, should we not instead use an "error method" that sends the relevant variables?

2017-06-22 07:01 UTC, Gathondu commented on healthtools/scrapers/base_scraper.py
>                  print "ERROR: scrape_site() - source: {} - page: {} - {}".format(url, page_num, err)
Makes sense

2017-06-22 08:56 UTC, merged