Scrape NHIF data
CodeForAfrica-SCRAPERS/healthtools_ke pull request #23
Opened 2017-07-11 14:18 UTC by Gathondu

#### What does this PR do?
Add scrapers for NHIF data
Add tests for NHIF scrapers
Update README
#### Description of Task to be completed?
Add Scrapers for NHIF accredited facilities and accredited inpatient facilities
#### How should this be manually tested?
run `nosetest --nocapture`
#### Any background context you want to provide?
Initially there were no scrapers for NHIF data online and now that it has been made available, this PR includes the scrapers for the same

2017-07-11 15:47 UTC, DavidLemayian commented on README.md
> +- NHIF accredited inpatient facilities: http://www.nhif.or.ke/healthinsurance/inpatientServices
💯 for the Readme update.

2017-07-11 15:48 UTC, DavidLemayian commented on README.md
> +- NHIF accredited inpatient facilities: http://www.nhif.or.ke/healthinsurance/inpatientServices
Thought the first link is "outpatient healthcare providers who will offer outpatient care to members of the Civil Service and Disciplined services and their declared defendants."

2017-07-11 15:52 UTC, DavidLemayian commented on README.md
> +- NHIF accredited inpatient facilities: http://www.nhif.or.ke/healthinsurance/inpatientServices
You can fin outpatient here - http://www.nhif.or.ke/healthinsurance/outpatientServices

2017-07-11 15:55 UTC, DavidLemayian requested changes
Considering the feedback on inpatient, outpatient, and outpatient civil servants, you might want to rename your classes first.

2017-07-11 15:55 UTC, DavidLemayian commented on healthtools/config.py
> +    "NHIF-INPATIENT": "http://www.nhif.or.ke/healthinsurance/inpatientServices"
Let's change the config names to follow the standard;
```
NHIF_INPATIENT
NHIF_OUTPATIENT
NHIF_OUTPATIENT_CS
```

2017-07-13 11:14 UTC, Gathondu commented on healthtools/scrapers/nhif_inpatient_facilities.py
> +        self.s3_key = "data/nhif_accredited_inpatient_facilities.json"
@DavidLemayian while archiving the new data to s3, it fails saying that this key doesn't exsist

2017-07-13 11:14 UTC, Gathondu commented on healthtools/scrapers/nhif_inpatient_facilities.py
> +        self.s3_historical_record_key = "data/archive/nhif_accredited_inpatient_facilities-{}.json"
and so does this one and the rest for the nhif scrapers

2017-07-14 09:26 UTC, DavidLemayian requested changes

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/scrapers/nhif_inpatient_facilities.py
> +        self.s3_key = "data/nhif_accredited_inpatient_facilities.json"
@Gathondu Did you solve this?

Let's name this file `data/nhif_inpatient.json` instead.

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/scrapers/nhif_inpatient_facilities.py
> +        self.s3_historical_record_key = "data/archive/nhif_accredited_inpatient_facilities-{}.json"
@Gathondu Let's name this `data/archive/nhif_inpatient-{}.json`

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/scrapers/nhif_outpatient_cs_facilities.py
> +        self.s3_historical_record_key = "data/archive/nhif_outpatient_cs_facilities-{}.json"
Let's name these `data/nhif_outpatient_cs.json`.

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/scrapers/nhif_outpatient_facilities.py
> +        self.s3_historical_record_key = "data/archive/nhif_accredited_outpatient_facilities-{}.json"
@Gathondu Let's name these `data/nhif_outpatient.json`.

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +from healthtools.scrapers.nhif_outpatient_facilities import NhifOutpatientScraper
@Gathondu Let's order these inpatient, outpatient, and outpatient-cs.

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +class TestScrapers(unittest.TestCase):
💯

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +        self.nhif_accredited_scraper = NhifOutpatientCsScraper()
Let's rename to `self.nhif_outpatient_cs_scraper`.

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +        with open(TEST_DIR + "/dummy_files/nhif_accredited_facilities.json", "r") as my_file:
This file will need a rename.

2017-07-14 09:26 UTC, DavidLemayian commented on scraper.py
> +    nhif_accredited_result = nhif_accredited_facilities.scrape_site()
Let's have this after the rest of the scrapers.

2017-07-14 09:26 UTC, DavidLemayian commented on scraper.py
> +    nhif_accredited_outpatient = NhifOutpatientScraper()
Let's rename these variables appropriately.

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +            self.assertEqual(response["items"][0]["index"]["_shards"]["successful"], 1)
Let's remove "facilities" in the names. It's redundant - "Inpatient", "Outpatient" already talks about a facility.

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/config.py
> +    "NHIF-OUTPATIENT_CS": "http://www.nhif.or.ke/healthinsurance/medicalFacilities",
Let's move this to the bottom of the list.

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/scrapers/base_scraper.py
> +        self.NHIF_SERVICES = ["accredited", "inpatient", "outpatient"]
These should be: inpatient, outpatient, outpatient-cs

2017-07-14 09:26 UTC, DavidLemayian commented on healthtools/scrapers/base_scraper.py
> +                "_index": ES["index"],
😱

2017-07-14 11:28 UTC, Gathondu commented on healthtools/scrapers/nhif_inpatient_facilities.py
> +        self.s3_key = "data/nhif_accredited_inpatient_facilities.json"
@DavidLemayian not yet, I don't have access to the aws to create the files, on renaming, on it 👍

2017-07-14 11:28 UTC, Gathondu commented on healthtools/scrapers/nhif_inpatient_facilities.py
> +        self.s3_historical_record_key = "data/archive/nhif_accredited_inpatient_facilities-{}.json"
👍

2017-07-14 11:32 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +from healthtools.scrapers.nhif_outpatient_facilities import NhifOutpatientScraper
👍

2017-07-14 11:33 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +class TestScrapers(unittest.TestCase):
👍

2017-07-14 11:34 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +        self.nhif_accredited_scraper = NhifOutpatientCsScraper()
👍

2017-07-14 11:36 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +        with open(TEST_DIR + "/dummy_files/nhif_accredited_facilities.json", "r") as my_file:
👍

2017-07-14 11:36 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +            self.assertEqual(response["items"][0]["index"]["_shards"]["successful"], 1)
👍

2017-07-14 11:36 UTC, Gathondu commented on scraper.py
> +    nhif_accredited_outpatient = NhifOutpatientScraper()
👍

2017-07-14 11:41 UTC, Gathondu commented on healthtools/scrapers/base_scraper.py
> +                "_index": ES["index"],
😲 🏃

2017-07-14 11:42 UTC, Gathondu commented on healthtools/scrapers/base_scraper.py
> +                "_index": ES["index"],
wait...it correct that one..i refactored the code

2017-07-15 13:25 UTC, DavidLemayian requested changes

2017-07-15 13:25 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +        self.nhif_outpatient_scraper = NhifOutpatientScraper()
Let's re-order this appropriately: inpatient, outpatient, outpatient-cs.

2017-07-15 13:25 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +    def test_it_scrapes_nhif_accredited_page(self):
This requires a rename?

2017-07-15 13:25 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +
Let's re-order these new functions appropriately.

2017-07-15 13:25 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +    def test_nhif_accredited_scraper_uploads_to_elasticsearch(self):
This requires a rename.

2017-07-15 13:25 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +
Let's re-order these appropriately.

2017-07-15 13:25 UTC, DavidLemayian commented on scraper.py
> +from healthtools.scrapers.nhif_outpatient import NhifOutpatientScraper
Let's re-order these.

2017-07-18 03:37 UTC, Gathondu commented
@DavidLemayian the changes to the above recommendations are in order

2017-07-23 08:51 UTC, merged