Develop
CodeForAfrica-SCRAPERS/healthtools_ke pull request #26
Opened 2017-08-01 08:31 UTC by Gathondu

#### What does this PR do?
Refactor tests for the scrapers
Refactor tests for the scraper tests

2017-08-01 08:40 UTC, DavidLemayian requested changes

2017-08-01 08:40 UTC, DavidLemayian commented on healthtools/config.py
> +TEST_DIR = os.getcwd() + "/healthtools/tests/"
Any reason why? The `TEST_DIR` is where the test data would go.

2017-08-02 14:55 UTC, Gathondu commented on healthtools/config.py
> +TEST_DIR = os.getcwd() + "/healthtools/tests/"
the `TEST_DIR` is where the json data files used are located

2017-08-02 15:11 UTC, DavidLemayian commented on healthtools/config.py
> +TEST_DIR = os.getcwd() + "/healthtools/tests/"
@Gathondu yeah, we're saying the same thing. So wouldn't it therefore go to the local data folder then? Or actually wherever the `DATA_DIR` is pointed to?

2017-08-02 16:38 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +        with open(TEST_DIR + "dummy_files/doctors.json", "r") as my_file:
@DavidLemayian this is what I mean. We have a folder in tests that has the dummy files

2017-08-02 16:40 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +        with open(TEST_DIR + "dummy_files/doctors.json", "r") as my_file:
the dummy files are supposed to act like data pulled from a scraper that the tests uses to test that it uploads

2017-08-02 17:25 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +        with open(TEST_DIR + "dummy_files/doctors.json", "r") as my_file:
@Gathondu And where would test data be downloaded to?

2017-08-02 18:20 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +        with open(TEST_DIR + "dummy_files/doctors.json", "r") as my_file:
@DavidLemayian to `DATA_DIR` but under a test folder

2017-08-07 07:57 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +        with open(TEST_DIR + "dummy_files/doctors.json", "r") as my_file:
@DavidLemayian back to this conversation, you see for the dummy data, it's included in the repo where as the data directory which is a substitute for the aws bucket, is ignored. That's why I strongly suggest having the dummy data not included in the data dir. Another work around would be to have the tests read from the archived data but as we know those are a lot of records that will delay the testing.

2017-08-07 08:00 UTC, DavidLemayian commented on healthtools/tests/test_scrapers.py
> +        with open(TEST_DIR + "dummy_files/doctors.json", "r") as my_file:
@Gathondu Yip. Sounds good. If the `TEST_DIR` doesn't change, should we therefore not have it config but instead just a constant in the test class?

2017-08-07 08:08 UTC, Gathondu commented on healthtools/tests/test_scrapers.py
> +        with open(TEST_DIR + "dummy_files/doctors.json", "r") as my_file:
@DavidLemayian makes sense. Let me refactor the code.

2017-08-07 15:13 UTC, closed without merging