Use argparse instead of sys.argv
CodeForAfrica-SCRAPERS/healthtools_ke pull request #39
Opened 2017-09-01 13:46 UTC by tinamorale

#### What does this PR do?
This PR fixes the open isuues:
    1. Use argparse instead #36
    2. Allow selection of what to scrape #34 
#### Description of Task to be completed?
A user can now select what to scrape. E.g.
`$ python scraper.py --small_batch --scraper doctors clinical_officers`

2017-09-01 16:00 UTC, DavidLemayian requested changes

2017-09-01 16:00 UTC, DavidLemayian commented on healthtools/scrapers/base_scraper.py
> +        parser.add_argument('-sb', '--small_batch', action="store_true",
Let's have this as `--small-batch`.

2017-09-04 07:25 UTC, tinamorale commented on healthtools/scrapers/base_scraper.py
> +        parser.add_argument('-sb', '--small_batch', action="store_true",
@DavidLemayian Changes done

2017-09-06 05:57 UTC, DavidLemayian approved these changes

2017-09-06 05:57 UTC, merged